### ISSUE TITLE
Allow empty pass field for Key-Based Authentication

### ISSUE THREAD

**Issue by ghost** [hesselbom/vim-hsftp#13] opened 2017-05-19 07:59 UTC
I think the title says it all. When uploading to a server which I can connect to via Key-Based Authentication the upload takes much longer, because the password is entered as invalid command after already logging in succesfully.

**Comment by hozza** [comment] 2019-09-07 15:15
Duplicate of #8

**Closed** 2019-09-13 16:15 UTC
Labels: request
